# Generated by Django 2.2.16 on 2022-11-01 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_auto_20221101_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='title',
            name='year',
            field=models.IntegerField(default=None, verbose_name='Дата выхода'),
        ),
    ]
